commands = {
        "ABOR" : "Abort",
        "ACCT" : "<account-information> Account",
        "ALLO" : "<decimal-integer> Allocate",
        "APPE" : "<pathname> Append (with create)",
        "CDUP" : "Change to parent directory",
        "CWD"  : "<pathname> Change working directory",
        "DELE" : "<pathname> Delete",
        "HELP" : "<command> Help",
        "LIST" : "<pathname> List",
        "MODE" : "<mode-type> Transfer mode",
        "MKD"  : "<pathname> Make directory",
        "NLST" : "<pathname> Name list",
        "NOOP" : "No operation (used to avoid disconnection) for inactivity",
        "PASS" : "<password> Password",
        "PASV" : "Passive",
        "PORT" : "<host-port> Data port",
        "PWD"  : "Print working directory",
        "QUIT" : "Logout",
        "REIN" : "Reinitialize",
        "REST" : "<marker> Restart",
        "RETR" : "<pathname> Retrieve",
        "RMD"  : "<pathname> Remove directory",
        "RNFR" : "<pathname> Rename from",
        "RNTO" : "<pathname> Rename to",
        "SITE" : "<command> Site parameters",
        "SMNT" : "<pathname> Structure mount",
        "STAT" : "<pathname> Status",
        "STOR" : "<pathname> Store",
        "STOU" : "<pathname> Store unique",
        "STRU" : "<structure-code> File structure",
        "SYST" : "System",
        "TYPE" : "<type> Representation type",
        "USER" : "<username> Username"
    }

response = {
        "1xx" : "Risposta positiva preliminare. L'azione richiesta è iniziata ma ci sarà un'altra risposta ad indicare che essa è effettivamente completata.",
        "2xx" : "Risposta positiva definitiva. L'azione richiesta è completata. Il client può ora mandare altri comandi.",
        "3xx" : "Risposta positiva intermedia. Il comando è stato accettato ma è necessario mandarne un secondo affinché la richiesta sia completata definitivamente.",
        "4xx" : "Risposta negativa temporanea. Il comando non è andato a buon fine ma potrebbe funzionare in un secondo momento.",
        "5xx" : "Risposta negativa definitiva. Il comando non è andato a buon fine e il client non dovrebbe più ripeterlo.",
        "x0x" : "Errore di sintassi.",
        "x1x" : "Risposta ad una richiesta informativa.",
        "x2x" : "Risposta relativa alla connessione.",
        "x3x" : "Risposta relativa all'account e/o ai permessi.",
        "x4x" : "Non meglio specificato.",
        "x5x" : "Risposta relativa al filterle-system."
    }
